
import Consola.ProcesosCalculadora;
public class Calculadora extends javax.swing.JFrame {
    ProcesosCalculadora consola= new ProcesosCalculadora();
    public float num1;
    public float num2;
    public float ans;
    public String ope;
    
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtOperacion = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonClean = new javax.swing.JButton();
        btn_Iva = new javax.swing.JButton();
        btn_Potencia9 = new javax.swing.JButton();
        btn_Raiz9 = new javax.swing.JButton();
        btn_Tan = new javax.swing.JButton();
        btn_Sen = new javax.swing.JButton();
        btn_Cos = new javax.swing.JButton();
        btn_Suma = new javax.swing.JButton();
        btn_Resta = new javax.swing.JButton();
        btn_Multiplicacion = new javax.swing.JButton();
        btn_Division = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_Decimal = new javax.swing.JButton();
        btn_Del = new javax.swing.JButton();
        btn_Igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(118, 16, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(219, 146, 134));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOperacion.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 50));

        txtResultado.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtResultado.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 290, 60));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 310, 150));

        jPanel2.setBackground(new java.awt.Color(238, 203, 197));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonClean.setBackground(new java.awt.Color(238, 203, 197));
        botonClean.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        botonClean.setForeground(new java.awt.Color(240, 240, 240));
        botonClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        botonClean.setText("C");
        botonClean.setBorder(null);
        botonClean.setContentAreaFilled(false);
        botonClean.setFocusPainted(false);
        botonClean.setFocusable(false);
        botonClean.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonClean.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        botonClean.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        botonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCleanActionPerformed(evt);
            }
        });
        jPanel2.add(botonClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_Iva.setBackground(new java.awt.Color(238, 203, 197));
        btn_Iva.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        btn_Iva.setForeground(new java.awt.Color(240, 240, 240));
        btn_Iva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Iva.setText("IVA");
        btn_Iva.setBorder(null);
        btn_Iva.setContentAreaFilled(false);
        btn_Iva.setFocusPainted(false);
        btn_Iva.setFocusable(false);
        btn_Iva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Iva.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Iva.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IvaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btn_Potencia9.setBackground(new java.awt.Color(238, 203, 197));
        btn_Potencia9.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        btn_Potencia9.setForeground(new java.awt.Color(240, 240, 240));
        btn_Potencia9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Potencia9.setText("X^9");
        btn_Potencia9.setBorder(null);
        btn_Potencia9.setContentAreaFilled(false);
        btn_Potencia9.setFocusPainted(false);
        btn_Potencia9.setFocusable(false);
        btn_Potencia9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Potencia9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Potencia9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Potencia9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Potencia9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Potencia9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btn_Raiz9.setBackground(new java.awt.Color(238, 203, 197));
        btn_Raiz9.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        btn_Raiz9.setForeground(new java.awt.Color(240, 240, 240));
        btn_Raiz9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Raiz9.setText("9√");
        btn_Raiz9.setBorder(null);
        btn_Raiz9.setContentAreaFilled(false);
        btn_Raiz9.setFocusPainted(false);
        btn_Raiz9.setFocusable(false);
        btn_Raiz9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Raiz9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Raiz9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Raiz9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Raiz9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Raiz9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        btn_Tan.setBackground(new java.awt.Color(238, 203, 197));
        btn_Tan.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        btn_Tan.setForeground(new java.awt.Color(240, 240, 240));
        btn_Tan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Tan.setText("Tan");
        btn_Tan.setBorder(null);
        btn_Tan.setContentAreaFilled(false);
        btn_Tan.setFocusPainted(false);
        btn_Tan.setFocusable(false);
        btn_Tan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Tan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Tan.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        btn_Sen.setBackground(new java.awt.Color(238, 203, 197));
        btn_Sen.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        btn_Sen.setForeground(new java.awt.Color(240, 240, 240));
        btn_Sen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Sen.setText("Sen");
        btn_Sen.setBorder(null);
        btn_Sen.setContentAreaFilled(false);
        btn_Sen.setFocusPainted(false);
        btn_Sen.setFocusable(false);
        btn_Sen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Sen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Sen.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Sen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SenActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Sen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        btn_Cos.setBackground(new java.awt.Color(238, 203, 197));
        btn_Cos.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        btn_Cos.setForeground(new java.awt.Color(240, 240, 240));
        btn_Cos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Cos.setText("Cos");
        btn_Cos.setBorder(null);
        btn_Cos.setContentAreaFilled(false);
        btn_Cos.setFocusPainted(false);
        btn_Cos.setFocusable(false);
        btn_Cos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Cos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Cos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        btn_Suma.setBackground(new java.awt.Color(238, 203, 197));
        btn_Suma.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_Suma.setForeground(new java.awt.Color(240, 240, 240));
        btn_Suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Suma.setText("+");
        btn_Suma.setBorder(null);
        btn_Suma.setContentAreaFilled(false);
        btn_Suma.setFocusPainted(false);
        btn_Suma.setFocusable(false);
        btn_Suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Suma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Suma.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        btn_Resta.setBackground(new java.awt.Color(238, 203, 197));
        btn_Resta.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_Resta.setForeground(new java.awt.Color(240, 240, 240));
        btn_Resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Resta.setText("-");
        btn_Resta.setBorder(null);
        btn_Resta.setContentAreaFilled(false);
        btn_Resta.setFocusPainted(false);
        btn_Resta.setFocusable(false);
        btn_Resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Resta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Resta.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RestaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        btn_Multiplicacion.setBackground(new java.awt.Color(238, 203, 197));
        btn_Multiplicacion.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btn_Multiplicacion.setForeground(new java.awt.Color(240, 240, 240));
        btn_Multiplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Multiplicacion.setText("X");
        btn_Multiplicacion.setBorder(null);
        btn_Multiplicacion.setContentAreaFilled(false);
        btn_Multiplicacion.setFocusPainted(false);
        btn_Multiplicacion.setFocusable(false);
        btn_Multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Multiplicacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Multiplicacion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiplicacionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        btn_Division.setBackground(new java.awt.Color(238, 203, 197));
        btn_Division.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_Division.setForeground(new java.awt.Color(240, 240, 240));
        btn_Division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Division.setText("/");
        btn_Division.setBorder(null);
        btn_Division.setContentAreaFilled(false);
        btn_Division.setFocusPainted(false);
        btn_Division.setFocusable(false);
        btn_Division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Division.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Division.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botona.png"))); // NOI18N
        btn_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivisionActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Division, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        btn_1.setBackground(new java.awt.Color(238, 203, 197));
        btn_1.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_1.setText("1");
        btn_1.setBorder(null);
        btn_1.setContentAreaFilled(false);
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 50));

        btn_2.setBackground(new java.awt.Color(238, 203, 197));
        btn_2.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_2.setText("2");
        btn_2.setBorder(null);
        btn_2.setContentAreaFilled(false);
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, 50));

        btn_3.setBackground(new java.awt.Color(238, 203, 197));
        btn_3.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_3.setText("3");
        btn_3.setBorder(null);
        btn_3.setContentAreaFilled(false);
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 50, 50));

        btn_4.setBackground(new java.awt.Color(238, 203, 197));
        btn_4.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_4.setText("4");
        btn_4.setBorder(null);
        btn_4.setContentAreaFilled(false);
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 50, 50));

        btn_5.setBackground(new java.awt.Color(238, 203, 197));
        btn_5.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_5.setText("5");
        btn_5.setBorder(null);
        btn_5.setContentAreaFilled(false);
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 50));

        btn_6.setBackground(new java.awt.Color(238, 203, 197));
        btn_6.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_6.setText("6");
        btn_6.setBorder(null);
        btn_6.setContentAreaFilled(false);
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 50, 50));

        btn_7.setBackground(new java.awt.Color(238, 203, 197));
        btn_7.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_7.setText("7");
        btn_7.setBorder(null);
        btn_7.setContentAreaFilled(false);
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 50));

        btn_8.setBackground(new java.awt.Color(238, 203, 197));
        btn_8.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_8.setText("8");
        btn_8.setBorder(null);
        btn_8.setContentAreaFilled(false);
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 50, 50));

        btn_9.setBackground(new java.awt.Color(238, 203, 197));
        btn_9.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_9.setText("9");
        btn_9.setBorder(null);
        btn_9.setContentAreaFilled(false);
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 50, 50));

        btn_0.setBackground(new java.awt.Color(238, 203, 197));
        btn_0.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_0.setText("0");
        btn_0.setBorder(null);
        btn_0.setContentAreaFilled(false);
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 50, 50));

        btn_Decimal.setBackground(new java.awt.Color(238, 203, 197));
        btn_Decimal.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_Decimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botonn.png"))); // NOI18N
        btn_Decimal.setText(".");
        btn_Decimal.setBorder(null);
        btn_Decimal.setContentAreaFilled(false);
        btn_Decimal.setFocusPainted(false);
        btn_Decimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Decimal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        btn_Decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DecimalActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 50, 50));

        btn_Del.setBackground(new java.awt.Color(238, 203, 197));
        btn_Del.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_Del.setForeground(new java.awt.Color(255, 255, 255));
        btn_Del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/del.png"))); // NOI18N
        btn_Del.setText("  X");
        btn_Del.setBorder(null);
        btn_Del.setContentAreaFilled(false);
        btn_Del.setFocusPainted(false);
        btn_Del.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Del.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dela.png"))); // NOI18N
        btn_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Del, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 50));

        btn_Igual.setBackground(new java.awt.Color(238, 203, 197));
        btn_Igual.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        btn_Igual.setForeground(new java.awt.Color(255, 255, 255));
        btn_Igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/igual.png"))); // NOI18N
        btn_Igual.setText("=");
        btn_Igual.setBorder(null);
        btn_Igual.setContentAreaFilled(false);
        btn_Igual.setFocusPainted(false);
        btn_Igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iguala.png"))); // NOI18N
        btn_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IgualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 50, 110));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 310, 310));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCleanActionPerformed
        txtOperacion.setText("");
        txtResultado.setText("");
        this.num1=0;
        this.num2=0;
        this.ans=0;
    }//GEN-LAST:event_botonCleanActionPerformed

    private void btn_IvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IvaActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="iva";
        this.txtOperacion.setText("");
    }//GEN-LAST:event_btn_IvaActionPerformed

    private void btn_Potencia9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Potencia9ActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="^";
        this.txtOperacion.setText("");
    }//GEN-LAST:event_btn_Potencia9ActionPerformed

    private void btn_Raiz9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Raiz9ActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="raiz";
        this.txtOperacion.setText("");
    }//GEN-LAST:event_btn_Raiz9ActionPerformed

    private void btn_TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TanActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="tangente";
        this.txtOperacion.setText("");
        this.btn_Igual.doClick();
    }//GEN-LAST:event_btn_TanActionPerformed

    private void btn_SenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SenActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="seno";
        this.txtOperacion.setText("");
        this.btn_Igual.doClick();
    }//GEN-LAST:event_btn_SenActionPerformed

    private void btn_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumaActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="+";
        this.txtOperacion.setText("");
    }//GEN-LAST:event_btn_SumaActionPerformed

    private void btn_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RestaActionPerformed

        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="-";
        this.txtOperacion.setText("");
    }//GEN-LAST:event_btn_RestaActionPerformed

    private void btn_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiplicacionActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="*";
        this.txtOperacion.setText("");
    }//GEN-LAST:event_btn_MultiplicacionActionPerformed

    private void btn_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivisionActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="/";
        this.txtOperacion.setText("");
    }//GEN-LAST:event_btn_DivisionActionPerformed

    private void btn_CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CosActionPerformed
        this.num1=Float.parseFloat(this.txtOperacion.getText());
        this.ope="coseno";
        this.txtOperacion.setText("");
        this.btn_Igual.doClick();
    }//GEN-LAST:event_btn_CosActionPerformed

    private void btn_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelActionPerformed
        if(this.txtOperacion.getText().length() !=0){
            this.txtOperacion.setText(this.txtOperacion.getText().substring(0,this.txtOperacion.getText().length()-1));
        }
    }//GEN-LAST:event_btn_DelActionPerformed

    private void btn_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IgualActionPerformed
        consola.setNum1(this.num1);
        switch(this.ope){
            case "+": this.txtOperacion.setText(Float.toString(consola.sumar()));
                this.num2=Float.parseFloat(this.txtOperacion.getText());
                consola.setNum2(this.num2);
                break;
            case "-": this.txtOperacion.setText(Float.toString(consola.restar()));
                this.num2=Float.parseFloat(this.txtOperacion.getText());
                consola.setNum2(this.num2);
                break;
            case "*": this.txtOperacion.setText(Float.toString(consola.multiplicar()));
                this.num2=Float.parseFloat(this.txtOperacion.getText());
                consola.setNum2(this.num2);
                break;
            case "/": this.txtOperacion.setText(Float.toString(consola.dividir()));
                this.num2=Float.parseFloat(this.txtOperacion.getText());
                consola.setNum2(this.num2);
                break;
            case "^": this.txtOperacion.setText(Float.toString(consola.potencia()));
                this.num2=Float.parseFloat(this.txtOperacion.getText());
                consola.setNum2(this.num2);
                break;
            case "raiz": this.txtOperacion.setText(Float.toString(consola.raiz()));
                this.num2=Float.parseFloat(this.txtOperacion.getText());
                consola.setNum2(this.num2);
                break;
            case "seno": this.txtOperacion.setText(Float.toString(consola.seno()));
                break;
            case "coseno": this.txtOperacion.setText(Float.toString(consola.coseno()));
                break;
            case "tangente": this.txtOperacion.setText(Float.toString(consola.tangente()));
                break;
            case "iva": this.txtOperacion.setText(Float.toString(consola.iva()));
                this.num2=Float.parseFloat(this.txtOperacion.getText());
                consola.setNum2(this.num2);
                break;
    }
    }//GEN-LAST:event_btn_IgualActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        addNumero("1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        addNumero("2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        addNumero("3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        addNumero("4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        addNumero("5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        addNumero("6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        addNumero("7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        addNumero("8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        addNumero("9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        addNumero("0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_DecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DecimalActionPerformed
     if(!(this.txtOperacion.getText().contains("."))){
         this.txtOperacion.setText(txtOperacion.getText()+("."));
     }
    }//GEN-LAST:event_btn_DecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
        
    }
    public void addNumero(String digito){
        txtOperacion.setText(txtOperacion.getText()+digito);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonClean;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_Cos;
    private javax.swing.JButton btn_Decimal;
    private javax.swing.JButton btn_Del;
    private javax.swing.JButton btn_Division;
    private javax.swing.JButton btn_Igual;
    private javax.swing.JButton btn_Iva;
    private javax.swing.JButton btn_Multiplicacion;
    private javax.swing.JButton btn_Potencia9;
    private javax.swing.JButton btn_Raiz9;
    private javax.swing.JButton btn_Resta;
    private javax.swing.JButton btn_Sen;
    private javax.swing.JButton btn_Suma;
    private javax.swing.JButton btn_Tan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
